# Generated by Django 5.2.5 on 2025-09-08 06:02

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='画像')),
                ('url', models.URLField(blank=True, null=True, verbose_name='作品URL')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日時')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開設定')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='カテゴリー')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='タグ')),
            ],
        ),
    ]
